// ============================================================
// F1 Fantasy - Core Type Definitions
// ============================================================

// --- Season Data Types (loaded from JSON generated by FastF1) ---

export interface QualifyingResult {
  driver: string;       // abbreviation e.g. "VER"
  fullName: string;
  team: string;
  position: number;
  q1: string | null;    // lap time string or null if no time set
  q2: string | null;
  q3: string | null;
  status: string;       // "Finished", "DSQ", etc.
}

export interface SprintResult {
  driver: string;
  fullName: string;
  team: string;
  grid: number;
  position: number;
  status: string;
  points: number;
}

export interface RaceResult {
  driver: string;
  fullName: string;
  team: string;
  grid: number;
  position: number;
  status: string;
  points: number;
}

export interface PitStopData {
  constructor: string;
  fastestStop: number;  // pit lane duration in seconds
}

export interface RoundData {
  round: number;
  raceName: string;
  country: string;
  date: string;
  isSprint: boolean;
  qualifying: {
    results: QualifyingResult[];
  };
  sprint: {
    results: SprintResult[];
    fastestLapDriver: string;
  } | null;
  race: {
    results: RaceResult[];
    fastestLapDriver: string;
    pitStops: PitStopData[];
    driverOfTheDay: string | null;
  };
}

export interface SeasonData {
  season: number;
  rounds: RoundData[];
}

// --- Game State Types ---

export type ChipType = 'extraDrs' | 'autopilot' | 'noNegative' | 'limitless' | 'wildcard';

export interface ChipStatus {
  extraDrs: boolean;   // true = still available
  autopilot: boolean;
  noNegative: boolean;
  limitless: boolean;
  wildcard: boolean;
}

export const ALL_CHIPS_AVAILABLE: ChipStatus = {
  extraDrs: true,
  autopilot: true,
  noNegative: true,
  limitless: true,
  wildcard: true,
};

// --- Market Assets ---

export interface DriverAsset {
  abbreviation: string;
  fullName: string;
  team: string;
  price: number;           // in millions (e.g. 30.0)
  fantasyPoints: number;   // cumulative season total
  recentScores: number[];  // last 3 round scores for form calculation
  lastPriceChange: number; // price change after last round (+/- in millions)
}

export interface ConstructorAsset {
  name: string;
  price: number;
  fantasyPoints: number;
  recentScores: number[];
  lastPriceChange: number;
}

// --- Manager / Team ---

export type AIStyle = 'fanatic' | 'value' | 'underdog';

export interface ManagerTeam {
  id: string;
  name: string;
  isHuman: boolean;
  aiStyle?: AIStyle;
  drivers: string[];          // 5 driver abbreviations
  constructors: string[];     // 2 constructor names
  drsBoostDriver: string;     // abbreviation of DRS boosted driver
  extraDrsDriver: string;     // abbreviation of 3X DRS driver when Extra DRS is armed
  activeChip: ChipType | null;
  chips: ChipStatus;
  totalPoints: number;
  weeklyPoints: number[];     // points scored each processed round
  budget: number;             // remaining budget in millions
  freeTransfers: number;
  lockedDrivers?: string[];
  lockedConstructors?: string[];
  // Limitless rollback state
  backupDrivers?: string[];
  backupConstructors?: string[];
  backupBudget?: number;
}

// --- Scoring Breakdown (for display) ---

export interface ScoreBreakdownItem {
  label: string;   // English display text
  labelZh: string; // Chinese display text
  points: number;
}

export interface DriverScoreBreakdown {
  qualifying: ScoreBreakdownItem[];
  sprint: ScoreBreakdownItem[];
  race: ScoreBreakdownItem[];
}

export interface ConstructorScoreBreakdown {
  qualifying: ScoreBreakdownItem[];
  sprint: ScoreBreakdownItem[];
  race: ScoreBreakdownItem[];
  pitStop: ScoreBreakdownItem[];
}

export interface DriverRoundScore {
  driver: string;
  qualifyingPoints: number;
  sprintPoints: number;
  racePoints: number;
  totalRaw: number;       // before DRS multiplier
  drsMultiplier: number;  // 1, 2, or 3
  totalFinal: number;     // after DRS multiplier
  breakdown?: DriverScoreBreakdown; // optional detail for the last-round popup
}

export interface ConstructorRoundScore {
  constructor: string;
  qualifyingPoints: number;
  sprintPoints: number;
  racePoints: number;
  pitStopPoints: number;
  total: number;
  breakdown?: ConstructorScoreBreakdown;
}

export interface ManagerRoundResult {
  managerId: string;
  driverScores: DriverRoundScore[];
  constructorScores: ConstructorRoundScore[];
  chipApplied: ChipType | null;
  transferPenalty: number;
  grossPoints: number;
  netPoints: number;
}

// --- UI State ---

export type GameView =
  | 'seasonSelect'
  | 'dashboard'
  | 'transfer'
  | 'standings'
  | 'seasonSummary';

export interface GameState {
  selectedSeason: number | null;
  seasonData: SeasonData | null;
  currentRound: number;
  drivers: DriverAsset[];
  constructors: ConstructorAsset[];
  managers: ManagerTeam[];
  currentView: GameView;
  isSeasonComplete: boolean;
  lastProcessedRound: number; // -1 = no round processed
  roundResults: ManagerRoundResult[][]; // results[roundIndex][managerIndex]
}

export const INITIAL_BUDGET = 100; // $100M
export const MAX_DRIVERS = 5;
export const MAX_CONSTRUCTORS = 2;
export const FREE_TRANSFERS_PER_ROUND = 2;
export const MAX_FREE_TRANSFERS = 3;
export const TRANSFER_PENALTY = -10;
export const PRICE_FLOOR = 3.0;   // $3M minimum
export const PRICE_CEILING = 35.0; // $35M maximum
export const PRICE_MAX_CHANGE = 1.0; // max $1.0M change per round
